# Generated by Django 5.2.5 on 2025-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alert_audio_alert_location_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskarea',
            name='latitude',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='riskarea',
            name='longitude',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
    ]
