# Generated by Django 5.2.5 on 2025-09-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_riskarea_latitude_alter_riskarea_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskarea',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='riskarea',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
